CREATE TABLE `call_recordings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`campaignId` int,
	`callLogId` int,
	`callQueueId` int,
	`agentId` int,
	`phoneNumber` varchar(20) NOT NULL,
	`contactName` varchar(200),
	`s3Key` varchar(512) NOT NULL,
	`s3Url` text NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`mimeType` varchar(50) NOT NULL DEFAULT 'audio/wav',
	`fileSize` int,
	`duration` int,
	`recordingType` enum('full','agent_only','caller_only','voicemail') NOT NULL DEFAULT 'full',
	`asteriskChannel` varchar(255),
	`mixMonitorId` varchar(255),
	`status` enum('recording','uploading','ready','failed','deleted') NOT NULL DEFAULT 'recording',
	`errorMessage` text,
	`consentObtained` int NOT NULL DEFAULT 0,
	`retainUntil` bigint,
	`deletedAt` bigint,
	`recordingStartedAt` bigint,
	`recordingEndedAt` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `call_recordings_id` PRIMARY KEY(`id`)
);
