CREATE TABLE `client_deployments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`serverIp` varchar(45) NOT NULL,
	`domain` varchar(255),
	`version` varchar(50),
	`environment` enum('production','staging','development') NOT NULL DEFAULT 'production',
	`status` enum('online','offline','degraded','maintenance','provisioning') NOT NULL DEFAULT 'provisioning',
	`lastHeartbeat` bigint,
	`sslExpiry` bigint,
	`diskUsagePercent` int,
	`memoryUsageMb` int,
	`cpuUsagePercent` int,
	`pbxHost` varchar(255),
	`pbxAgentVersion` varchar(50),
	`bridgeStatus` enum('connected','disconnected','unknown') NOT NULL DEFAULT 'unknown',
	`notes` text,
	`contactEmail` varchar(320),
	`contactPhone` varchar(20),
	`installedAt` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `client_deployments_id` PRIMARY KEY(`id`)
);
