CREATE TABLE `collection_import_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`sourceType` enum('csv','dakcs','latitude','collectbank','custom') NOT NULL DEFAULT 'csv',
	`fileName` varchar(255),
	`fileSize` int,
	`s3Key` varchar(512),
	`s3Url` text,
	`fieldMapping` json,
	`targetListId` int,
	`createNewList` int NOT NULL DEFAULT 0,
	`newListName` varchar(255),
	`skipDuplicates` int NOT NULL DEFAULT 1,
	`updateExisting` int NOT NULL DEFAULT 0,
	`debtFields` json,
	`status` enum('pending','validating','importing','completed','failed') NOT NULL DEFAULT 'pending',
	`totalRows` int NOT NULL DEFAULT 0,
	`importedRows` int NOT NULL DEFAULT 0,
	`skippedRows` int NOT NULL DEFAULT 0,
	`failedRows` int NOT NULL DEFAULT 0,
	`errorLog` json,
	`errorMessage` text,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `collection_import_jobs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `settlement_offers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`contactId` int NOT NULL,
	`tierId` int NOT NULL,
	`campaignId` int,
	`callLogId` int,
	`originalBalance` int NOT NULL,
	`discountPercent` int NOT NULL,
	`settlementAmount` int NOT NULL,
	`paymentDeadline` bigint,
	`status` enum('pending','presented','accepted','declined','expired','paid','partial_paid','voided') NOT NULL DEFAULT 'pending',
	`amountPaid` int DEFAULT 0,
	`paidAt` bigint,
	`installmentPlan` json,
	`notes` text,
	`declineReason` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `settlement_offers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `settlement_tiers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`minDebtAge` int,
	`maxDebtAge` int,
	`minBalance` int,
	`maxBalance` int,
	`discountPercent` int NOT NULL,
	`paymentDeadlineDays` int NOT NULL DEFAULT 30,
	`allowInstallments` int NOT NULL DEFAULT 0,
	`maxInstallments` int DEFAULT 1,
	`scriptTemplate` text,
	`priority` int NOT NULL DEFAULT 1,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `settlement_tiers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `skip_trace_phones` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestId` int NOT NULL,
	`contactId` int,
	`phoneNumber` varchar(20) NOT NULL,
	`phoneType` varchar(20),
	`phoneStatus` varchar(20),
	`confidence` int NOT NULL DEFAULT 0,
	`isApplied` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `skip_trace_phones_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `skip_trace_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`contactId` int,
	`contactListId` int,
	`provider` varchar(50) NOT NULL,
	`requestType` enum('single','batch') NOT NULL DEFAULT 'single',
	`inputFirstName` varchar(100),
	`inputLastName` varchar(100),
	`inputPhone` varchar(20),
	`inputAddress` text,
	`inputSsn4` varchar(4),
	`status` enum('pending','processing','completed','failed','no_results') NOT NULL DEFAULT 'pending',
	`resultsCount` int NOT NULL DEFAULT 0,
	`results` json,
	`costCents` int DEFAULT 0,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `skip_trace_requests_id` PRIMARY KEY(`id`)
);
